const $w=s=>document.querySelector(s);
const shortW=a=>a.slice(0,6)+'…'+a.slice(-6);
const escW=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bar(label,value,max){return `<div class="wscore-row"><span>${label}</span><div class="wbar"><i style="width:${Math.round(value/max*100)}%"></i></div><b>${value}/${max}</b></div>`}
function renderWallet(d){
 const s=d.score, pct=s.total;
 $w('#walletResult').hidden=false;
 $w('#walletResult').innerHTML=`<div class="wallet-head"><div><span class="wallet-label">wallet profile</span><h2 class="wallet-address">${shortW(escW(d.address))}</h2><a class="monoaddr" target="_blank" rel="noopener" href="https://solscan.io/account/${encodeURIComponent(d.address)}">view on solscan ↗</a></div><div class="wallet-tier ${d.tier}">${d.tier}<strong>${pct}</strong><small>/ 100</small></div></div><div class="wallet-grid"><div class="panel wallet-score"><h3>quality score</h3>${bar('sample',s.sample,25)}${bar('activity',s.activity,20)}${bar('diversity',s.diversity,20)}${bar('position spread',s.concentration,20)}${bar('capital',s.capital,15)}</div><div class="panel wallet-facts"><h3>observed footprint</h3><div><span>recent transactions</span><b>${d.sample.transactions}${d.sample.capped?'+' : ''}</b></div><div><span>non-zero token accounts</span><b>${d.holdings.tokens}</b></div><div><span>SOL balance</span><b>${d.holdings.sol.toFixed(3)}</b></div><div><span>last activity</span><b>${d.lastActivity?new Date(d.lastActivity*1000).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'}</b></div></div></div><div class="wallet-limit"><b>what this does not claim yet</b><ul>${d.limitations.map(x=>`<li>${escW(x)}</li>`).join('')}</ul></div>`;
}
async function analyze(){const input=$w('#walletInput'),out=$w('#walletResult'),btn=$w('#walletGo'),a=input.value.trim();if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(a)){out.hidden=false;out.innerHTML='<p class="scan-err">wallet address gak valid.</p>';return}btn.disabled=true;out.hidden=false;out.innerHTML='<p class="muted pad">reading public Solana footprint…</p>';try{const r=await fetch('/api/wallet?address='+encodeURIComponent(a));const d=await r.json();if(!r.ok)throw Error(d.error);renderWallet(d)}catch(e){out.innerHTML='<p class="scan-err">wallet data unavailable — coba lagi sebentar.</p>'}finally{btn.disabled=false}}
$w('#walletGo').addEventListener('click',analyze);$w('#walletInput').addEventListener('keydown',e=>{if(e.key==='Enter')analyze()});
